### ISSUE TITLE
Add support for CLI features options

### ISSUE THREAD

**Issue by Roms1383** [crate-ci/cargo-ghp-upload#48]
First time here, your Github Action looks great and was exactly what I was looking for, except ...

#### What problem are you having?

When building docs, we often have to enable / disable different `feature flags`, especially in a workspace.

#### What do you expect to happen ?

Adding another CLI arg to pipe the features options, as per `cargo doc`: [Command line features options](https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options) would be a must ! 🙏

Thanks :)

**Comment by epage** [comment]
I think you might have the wrong project.  We haven't touched this project in over 3 years and do not have any github actions.  This project is predates docs.rs and has basically been ignored since that became popular.

**Comment by Roms1383** [comment]
Oh ok my bad !
